//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About AudioMemo.
        /// </summary>
        internal static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average points.
        /// </summary>
        internal static string AveragePointsLabel {
            get {
                return ResourceManager.GetString("AveragePointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rounds.
        /// </summary>
        internal static string AverageRoundsLabel {
            get {
                return ResourceManager.GetString("AverageRoundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birds.
        /// </summary>
        internal static string BirdsSoundScheme {
            get {
                return ResourceManager.GetString("BirdsSoundScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus time!.
        /// </summary>
        internal static string BonusTimeAlert {
            get {
                return ResourceManager.GetString("BonusTimeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string CardField {
            get {
                return ResourceManager.GetString("CardField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked card.
        /// </summary>
        internal static string CardPickedField {
            get {
                return ResourceManager.GetString("CardPickedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games count.
        /// </summary>
        internal static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort this game?.
        /// </summary>
        internal static string DoAbortGameTitle {
            get {
                return ResourceManager.GetString("DoAbortGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended.
        /// </summary>
        internal static string GameEndedLabel {
            get {
                return ResourceManager.GetString("GameEndedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game will be lost..
        /// </summary>
        internal static string GameWillBeLostLabel {
            get {
                return ResourceManager.GetString("GameWillBeLostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioMemo on GitHub.
        /// </summary>
        internal static string GithubButton {
            get {
                return ResourceManager.GetString("GithubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        internal static string InstrumentsSoundScheme {
            get {
                return ResourceManager.GetString("InstrumentsSoundScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full license.
        /// </summary>
        internal static string LicenseButton {
            get {
                return ResourceManager.GetString("LicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum points.
        /// </summary>
        internal static string MaxPointsLabel {
            get {
                return ResourceManager.GetString("MaxPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum rounds.
        /// </summary>
        internal static string MaxRoundsLabel {
            get {
                return ResourceManager.GetString("MaxRoundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string NewGameButton {
            get {
                return ResourceManager.GetString("NewGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano.
        /// </summary>
        internal static string PianoSoundScheme {
            get {
                return ResourceManager.GetString("PianoSoundScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string PointsLabel {
            get {
                return ResourceManager.GetString("PointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining cards.
        /// </summary>
        internal static string RemainingCardsLabel {
            get {
                return ResourceManager.GetString("RemainingCardsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        internal static string RoundLabel {
            get {
                return ResourceManager.GetString("RoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec..
        /// </summary>
        internal static string SecondsAlert {
            get {
                return ResourceManager.GetString("SecondsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sound scheme.
        /// </summary>
        internal static string SelectSoundSchemeTitle {
            get {
                return ResourceManager.GetString("SelectSoundSchemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ended!.
        /// </summary>
        internal static string TimeEndedAlert {
            get {
                return ResourceManager.GetString("TimeEndedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is over, congratulations!
        ///You are now ready to play!.
        /// </summary>
        internal static string TutorialEndHint {
            get {
                return ResourceManager.GetString("TutorialEndHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is what it is all about!
        ///Of course, there were only two cards here. It gets a bit more complicated when the board is bigger and there are more cards.
        ///The board is now three by three and there are four cards on it. Try it!.
        /// </summary>
        internal static string TutorialFirstPairHint {
            get {
                return ResourceManager.GetString("TutorialFirstPairHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the card has been unveiled. The unveiling of each card causes some sound to be played. The object of the game is to find the second card that corresponds to the same sound.
        ///Only one card remains on the board, so this task should not be particularly challenging..
        /// </summary>
        internal static string TutorialFirstPickHint {
            get {
                return ResourceManager.GetString("TutorialFirstPickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AudioMemo game!
        ///This game is based on the popular Memory game, which goal is pairing cards. In this case, the patterns have been replaced by sounds.
        ///The screen now displays a 2 by 2 board. Two of fields are empty, marked with a circle figure. The other two, containing squares, hide cards.
        ///Tip for screen reader users: When playing the game, it is advisable to move your finger around the screen instead of using the item by item navigation.
        ///When you tap on a card, the card is revealed. Try to do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialStartHint {
            get {
                return ResourceManager.GetString("TutorialStartHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole challenge is to remember the positions of as many cards as possible.
        ///This pays off not only because it speeds up the collection of pairs and, well, time is limited, but also because two pairs collected in a row means bonus time.
        ///Let&apos;s turn up the difficulty level a little. Now the board is four by four, and there are 10 cards on it. Can you do it?.
        /// </summary>
        internal static string TutorialThirdPairHint {
            get {
                return ResourceManager.GetString("TutorialThirdPairHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string TutorialTitle {
            get {
                return ResourceManager.GetString("TutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins count.
        /// </summary>
        internal static string WinsLabel {
            get {
                return ResourceManager.GetString("WinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win on the previous scheme to unlock this one..
        /// </summary>
        internal static string WinToUnlockLabel {
            get {
                return ResourceManager.GetString("WinToUnlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
